---
# Copyright (c) 2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Antora Playbook building current Git HEAD and all `v*` branches.
#
# See: https://docs.antora.org/antora/latest/playbook/
#
site:
  url: https://redhat-documentation.github.io/vale-at-red-hat
  title: Vale for writers at Red Hat
  start_page: docs::index.adoc
  robots: allow
content:
  sources:
    - url: ./
      branches:
        - HEAD
        - v*
      edit_url: "https://github.com/redhat-documentation/vale-at-red-hat/edit/{refname}/{path}"
antora:
  extensions:
    - require: "@antora/lunr-extension" # https://gitlab.com/antora/antora-lunr-extension/
asciidoc:
  attributes:
    context: docs
  sourcemap: true
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
  output_dir: _
urls:
  html_extension_style: indexify
  latest_version_segment_strategy: replace
  redirect_facility: static
output:
  destinations:
    - provider: fs
      clean: true
      path: build/vale-at-red-hat/
runtime:
  log:
    level: info
    failure_level: warn
    format: pretty
  fetch: true
  cache_dir: ./.cache/antora

